#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobile.App.Resource", IsApplication=true)]

namespace Mobile.App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.Identity.Client.Resource.Id.agentWebView = global::Mobile.App.Resource.Id.agentWebView;
			global::Microsoft.Identity.Client.Resource.Layout.WebAuthenticationBroker = global::Mobile.App.Resource.Layout.WebAuthenticationBroker;
			global::Microsoft.Identity.Client.Resource.String.ApplicationName = global::Mobile.App.Resource.String.ApplicationName;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Id.agentWebView = global::Mobile.App.Resource.Id.agentWebView;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Layout.WebAuthenticationBroker = global::Mobile.App.Resource.Layout.WebAuthenticationBroker;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.String.ApplicationName = global::Mobile.App.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.ApplicationName = global::Mobile.App.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::Mobile.App.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int red = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CDSm = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int Text = 2131165195;
			
			// aapt resource value: 0x7f070022
			public const int agentWebView = 2131165218;
			
			// aapt resource value: 0x7f07000d
			public const int alertCreatedDateListItem = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int alertListView = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int alertTypeListItem = 2131165196;
			
			// aapt resource value: 0x7f07001f
			public const int appLogo = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int buttonAlertList = 2131165214;
			
			// aapt resource value: 0x7f070012
			public const int buttonConfirmCreateAlert = 2131165202;
			
			// aapt resource value: 0x7f07001d
			public const int buttonCreateAlert = 2131165213;
			
			// aapt resource value: 0x7f070020
			public const int buttonLoginUser = 2131165216;
			
			// aapt resource value: 0x7f070013
			public const int buttonStartShipment = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int buttonStopShipment = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int descriptionTextHeader = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int descriptionTextValue = 2131165201;
			
			// aapt resource value: 0x7f070023
			public const int item1 = 2131165219;
			
			// aapt resource value: 0x7f07000f
			public const int spinnerAlertType = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int textAlertItemCreatedDateHeader = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int textAlertItemCreatedDateValue = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int textAlertItemDescriptionHeader = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int textAlertItemDescriptionValue = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int textAlertItemSeverityLevelHeader = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int textAlertItemSeverityLevelValue = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int textAlertItemStatusHeader = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int textAlertItemStatusValue = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int textAlertItemTypeHeader = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int textAlertItemTypeValue = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int textAlertTypeHeader = 2131165198;
			
			// aapt resource value: 0x7f070017
			public const int textDrivingTimeOneDay = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int textDrivingTimeOneDayValue = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int textDrivingTimeSevenDays = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int textDrivingTimeSevenDaysValue = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int textRestingTimeLeftBeforeNewTransportation = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int textRestingTimeLeftBeforeNewTransportationValue = 2131165212;
			
			// aapt resource value: 0x7f070015
			public const int textTimeLeftBeforeRestHeader = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int textTimeLeftBeforeRestValue = 2131165206;
			
			// aapt resource value: 0x7f070021
			public const int textViewLoginResult = 2131165217;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlertItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AlertList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AlertListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateAlert = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DriverTrackingView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int WebAuthenticationBroker = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int alert_popup = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040010
			public const int alert_description_header_text = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int alert_item_created_date_header_text = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int alert_item_description_header_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int alert_item_severity_level_header_text = 2130968596;
			
			// aapt resource value: 0x7f040011
			public const int alert_item_status_header_text = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int alert_item_type_header_text = 2130968595;
			
			// aapt resource value: 0x7f040009
			public const int alert_list_button_text = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int alert_type_header_text = 2130968591;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int confirm_create_alert_button_text = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int create_alert_button_text = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int driver_tracking_button_text = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int driving_time_one_day_text = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int driving_time_seven_days_text = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int empty_text = 2130968590;
			
			// aapt resource value: 0x7f040003
			public const int login_button_text = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int resting_time_left_text = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int start_shipment_button_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int stop_shipment_button_text = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int time_left_before_rest_text = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
